language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
          env:
            - CMAKE_OPTIONS=""
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
            - libfftw3-dev
          env:
            - CMAKE_OPTIONS="-DENABLE_FFTW=ON"

before_script:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
    - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 100

script:
    - eval "cmake . ${CMAKE_OPTIONS}"
    - make 
    - make test CTEST_OUTPUT_ON_FAILURE=1
