language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - gfortran-7
      env: GCC_VER="7" CMAKE_CC=gcc-7 CMAKE_FC=gfortran-7"

script:
        CC=CMAKE_CC && FC=CMAKE_FC && cmake . && make && make test
