language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
          env:
            - MY_CMAKE_OPTIONS=""
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
            - libfftw3-dev
          env:
            - MY_CMAKE_OPTIONS="-DENABLE_FFTW=ON"

before_script:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
    - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 100
    - mkdir build
    - cd build
    - echo $MY_CMAKE_OPTIONS
 
script:
    - cmake .. $MY_CMAKE_OPTIONS
    - make 
    - make test CTEST_OUTPUT_ON_FAILURE=1
