language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
      env:
        - MATRIX_EVAL="CC=/usr/bin/gcc-5 && FC=/usr/bin/gfortran-5"

script: cmake . && make && make test

before_install:
    - eval "${MATRIX_EVAL}"
