language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
          script:
            - cmake ..
            - make 
            - make test CTEST_OUTPUT_ON_FAILURE=1
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
            - libfftw3-dev
        script:
            - cmake .. -DENABLE_FFTW=ON
            - make 
            - make test CTEST_OUTPUT_ON_FAILURE=1

before_script:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100
    - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-5 100
    - mkdir build
    - cd build


