language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gfortran-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && FC=gfortran-5"

script: cmake . && make && make test

before_install:
    - eval "${MATRIX_EVAL}"
