/*
 * This file is part of FNFT.
 *
 * FNFT is free software; you can redistribute it and/or
 * modify it under the terms of the version 2 of the GNU General
 * Public License as published by the Free Software Foundation.
 *
 * FNFT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * Contributors:
 * Igor Chekhovskoy 2026.
 * Irina Vaseva 2026.
 */
#define FNFT_ENABLE_SHORT_NAMES

#include "fnft__nse_scatter.h"
#include "fnft__nse_discretization.h"
#include "fnft__misc.h"
#include "fnft__errwarn.h"

#include <stdlib.h>

/* Values generated by the independent NFT_ES8 implementation in integrate.h,
 * which is a direct transcription of Eqs. 51--60 of arXiv:2608.11892v1. */
static INT test_paper_coefficients(void)
{
    const COMPLEX q[7] = {0.13 + 0.02 * I,    -0.07 + 0.03 * I,   0.011 - 0.04 * I,
                          0.021 + 0.013 * I,  -0.008 + 0.006 * I, 0.003 - 0.002 * I,
                          -0.001 + 0.0004 * I};
    const COMPLEX r[7] = {-0.09 + 0.04 * I,   0.05 + 0.01 * I,   -0.014 - 0.009 * I,
                          0.006 - 0.003 * I,  0.002 + 0.004 * I, -0.001 - 0.0007 * I,
                          0.0003 + 0.0002 * I};
    const COMPLEX expected[24] = {-0.00010639014375158731 - 0.00064626268636944456 * I,
                                  0.13045199977447222 + 0.01833438298798809 * I,
                                  -0.090581002308626979 + 0.039624854004361117 * I,
                                  0.00010639014375158731 + 0.00064626268636944456 * I,
                                  6.6029439153439124e-6 - 0.99993973629338628 * I,
                                  -0.0050608385946560846 - 0.011587297410899472 * I,
                                  0.0016534792394444454 - 0.0083654412335978836 * I,
                                  -6.6029439153439124e-6 + 0.99993973629338628 * I,
                                  -7.1421507936507912e-6 - 4.4202031746031749e-5 * I,
                                  -6.0792142857142867e-5 + 0.00022172208994708997 * I,
                                  7.7978121693121703e-5 + 4.9306851851851839e-5 * I,
                                  7.1421507936507912e-6 + 4.4202031746031749e-5 * I,
                                  1.0079365079365077e-6 + 7.7698412698412717e-6 * I,
                                  -0.00033721005291005281 - 0.00077524708994708999 * I,
                                  0.00011042063492063491 - 0.00055814074074074071 * I,
                                  -1.0079365079365077e-6 - 7.7698412698412717e-6 * I,
                                  -6.3492063492063518e-7 - 4.1269841269841268e-6 * I,
                                  -5.8201058201058197e-6 + 2.1164021164021168e-5 * I,
                                  7.4074074074074083e-6 + 4.7619047619047624e-6 * I,
                                  6.3492063492063518e-7 + 4.1269841269841268e-6 * I,
                                  0.0,
                                  -3.1746031746031745e-5 - 7.4074074074074087e-5 * I,
                                  1.0582010582010584e-5 - 5.2910052910052919e-5 * I,
                                  0.0};
    const COMPLEX lambda = 0.31 + 0.17 * I;
    const COMPLEX expected_U[4] = {1.0151223081156064 - 0.039982507188694998 * I,
                                   0.13020129924855509 + 0.017752739161081763 * I,
                                   -0.090134938490682354 + 0.039208908505235708 * I,
                                   0.97121375302911384 + 0.041705781954501898 * I};
    COMPLEX coeff[24], U[4];
    fnft__akns_es8_z_coefficients(q, r, coeff);
    if (misc_rel_err(24, coeff, expected) > 10 * EPSILON)
        return E_TEST_FAILED;
    if (nse_scatter_matrix(7, q, r, 0.13, +1, 1, &lambda, U, NULL, nse_discretization_ES8, 0) !=
        SUCCESS)
        return E_TEST_FAILED;
    return misc_rel_err(4, U, expected_U) <= 20 * EPSILON ? SUCCESS : E_TEST_FAILED;
}

static void es8_pack(COMPLEX const f[7], REAL const h, COMPLEX out[7])
{
    out[0] = h * f[3];
    out[1] = h * (-f[0] / 60.0 + 3.0 * f[1] / 20.0 - 3.0 * f[2] / 4.0 + 3.0 * f[4] / 4.0 -
                  3.0 * f[5] / 20.0 + f[6] / 60.0);
    out[2] = h * (f[0] / 90.0 - 3.0 * f[1] / 20.0 + 3.0 * f[2] / 2.0 - 49.0 * f[3] / 18.0 +
                  3.0 * f[4] / 2.0 - 3.0 * f[5] / 20.0 + f[6] / 90.0);
    out[3] = h * (f[0] / 8.0 - f[1] + 13.0 * f[2] / 8.0 - 13.0 * f[4] / 8.0 + f[5] - f[6] / 8.0);
    out[4] = h * (-f[0] / 6.0 + 2.0 * f[1] - 13.0 * f[2] / 2.0 + 28.0 * f[3] / 3.0 -
                  13.0 * f[4] / 2.0 + 2.0 * f[5] - f[6] / 6.0);
    out[5] = h * (-f[0] / 2.0 + 2.0 * f[1] - 5.0 * f[2] / 2.0 + 5.0 * f[4] / 2.0 - 2.0 * f[5] +
                  f[6] / 2.0);
    out[6] = h * (f[0] - 6.0 * f[1] + 15.0 * f[2] - 20.0 * f[3] + 15.0 * f[4] - 6.0 * f[5] + f[6]);
}

static INT test_stencil_and_boundaries(void)
{
    const REAL h = 0.07;
    const COMPLEX samples[7] = {0.17 - 0.03 * I, 0.25 + 0.07 * I, 0.38 - 0.11 * I, 0.51 + 0.09 * I,
                                0.47 - 0.05 * I, 0.34 + 0.02 * I, 0.21 - 0.08 * I};
    const COMPLEX left_samples[7] = {0.0, 0.0, 0.0, samples[0], samples[1], samples[2], samples[3]};
    COMPLEX expected[7], *q_preprocessed = NULL, *r_preprocessed = NULL;
    UINT Dsub = 7, first_last_index[2];
    INT ret_code;

    ret_code = nse_discretization_preprocess_signal(7, samples, h, +1, &Dsub, &q_preprocessed,
                                                    &r_preprocessed, first_last_index,
                                                    nse_discretization_ES8);
    CHECK_RETCODE(ret_code, leave_fun);
    if (Dsub != 7 || first_last_index[0] != 0 || first_last_index[1] != 6) {
        ret_code = E_TEST_FAILED;
        goto leave_fun;
    }
    es8_pack(samples, h, expected);
    if (misc_rel_err(7, &q_preprocessed[21], expected) > 20 * EPSILON) {
        ret_code = E_TEST_FAILED;
        goto leave_fun;
    }
    es8_pack(left_samples, h, expected);
    if (misc_rel_err(7, q_preprocessed, expected) > 20 * EPSILON)
        ret_code = E_TEST_FAILED;
leave_fun:
    free(q_preprocessed);
    free(r_preprocessed);
    return ret_code;
}

static INT test_step(const INT kappa)
{
    const REAL h = 0.13, delta = 1e-6;
    const COMPLEX lambda = 0.31 + 0.17 * I;
    const COMPLEX real_lambda = 0.31;
    const COMPLEX samples[7] = {0.31 - 0.11 * I, 0.43 + 0.07 * I, 0.48 - 0.05 * I, 0.53 + 0.14 * I,
                                0.46 - 0.19 * I, 0.39 + 0.08 * I, 0.28 - 0.03 * I};
    COMPLEX rsamples[7], q[7], r[7], M[8], Mp[4], Mm[4], Mn[4];
    INT W = 0, ret_code;
    for (UINT i = 0; i < 7; i++)
        rsamples[i] = -kappa * CONJ(samples[i]);
    es8_pack(samples, h, q);
    es8_pack(rsamples, h, r);
    ret_code =
        nse_scatter_matrix(7, q, r, h, kappa, 1, &lambda, M, NULL, nse_discretization_ES8, 1);
    CHECK_RETCODE(ret_code, leave_fun);
    {
        const COMPLEX lp = lambda + delta, lm = lambda - delta;
        ret_code =
            nse_scatter_matrix(7, q, r, h, kappa, 1, &lp, Mp, NULL, nse_discretization_ES8, 0);
        CHECK_RETCODE(ret_code, leave_fun);
        ret_code =
            nse_scatter_matrix(7, q, r, h, kappa, 1, &lm, Mm, NULL, nse_discretization_ES8, 0);
        CHECK_RETCODE(ret_code, leave_fun);
    }
    for (UINT i = 0; i < 4; i++)
        Mp[i] = (Mp[i] - Mm[i]) / (2.0 * delta);
    if (misc_rel_err(4, &M[4], Mp) > 2e-9)
        return E_TEST_FAILED;
    ret_code =
        nse_scatter_matrix(7, q, r, h, kappa, 1, &real_lambda, Mn, NULL, nse_discretization_ES8, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    if (FABS(CABS(Mn[0]) * CABS(Mn[0]) + kappa * CABS(Mn[1]) * CABS(Mn[1]) - 1.0) > 1e-12)
        return E_TEST_FAILED;
    ret_code = nse_scatter_matrix(7, q, r, h, kappa, 1, &lambda, Mn, &W, nse_discretization_ES8, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    for (UINT i = 0; i < 4; i++)
        Mn[i] *= POW(2, W);
    if (misc_rel_err(4, M, Mn) > 100 * EPSILON)
        return E_TEST_FAILED;
leave_fun:
    return ret_code;
}

static INT test_constant_and_zero(const INT kappa)
{
    const REAL h = 0.09;
    const COMPLEX lambda = 0.41, value = 0.32 - 0.09 * I;
    COMPLEX samples[7], rsamples[7], q[7], r[7], es8[4], bo[4];
    INT ret_code;
    for (UINT i = 0; i < 7; i++) {
        samples[i] = value;
        rsamples[i] = -kappa * CONJ(value);
    }
    es8_pack(samples, h, q);
    es8_pack(rsamples, h, r);
    ret_code =
        nse_scatter_matrix(7, q, r, h, kappa, 1, &lambda, es8, NULL, nse_discretization_ES8, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    ret_code = nse_scatter_matrix(1, samples, rsamples, h, kappa, 1, &lambda, bo, NULL,
                                  nse_discretization_BO, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    if (misc_rel_err(4, es8, bo) > 100 * EPSILON)
        return E_TEST_FAILED;
    memset(q, 0, sizeof(q));
    memset(r, 0, sizeof(r));
    ret_code =
        nse_scatter_matrix(7, q, r, h, kappa, 1, &lambda, es8, NULL, nse_discretization_ES8, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    bo[0] = CEXP(-I * lambda * h);
    bo[1] = bo[2] = 0.0;
    bo[3] = CEXP(I * lambda * h);
    if (misc_rel_err(4, es8, bo) > 100 * EPSILON)
        return E_TEST_FAILED;
leave_fun:
    return ret_code;
}

INT main(void)
{
    const COMPLEX q_bad[6] = {0}, r_bad[6] = {0}, lambda = 0.3;
    COMPLEX result[4];
    INT ret_code;
    ret_code = test_paper_coefficients();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_stencil_and_boundaries();
    CHECK_RETCODE(ret_code, failure);
    if (nse_scatter_matrix(6, q_bad, r_bad, 0.1, +1, 1, &lambda, result, NULL,
                           nse_discretization_ES8, 0) == SUCCESS)
        return EXIT_FAILURE;
    ret_code = test_step(+1);
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_step(-1);
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_constant_and_zero(+1);
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_constant_and_zero(-1);
    CHECK_RETCODE(ret_code, failure);
    return EXIT_SUCCESS;
failure:
    return EXIT_FAILURE;
}
