% MEX_FNFT_KDVP_FLOQUET Computes the Floquet discriminant and the element
% alpha_21(E) of the monodromy matrix used to determine the nonlinear Fourier
% transform for the Korteweg-de Vries equation with periodic boundaries.
% Note: Currently the option 'grid_spacing' must be set.
%
%   [DEL, al21] = MEX_FNFT_KDVP_FLOQUET(q, T, E, OPTIONAL INPUTS)
%
% DESCRIPTION
%   Provides an interface to the C routine fnft_kdvp_floquet.
%
% INPUTS
%   q               Complex row vector of length D>1
%   T               Real 1x2 vector
%   E               Real 1x2 vector
%
% OPTIONAL INPUTS
%   It is possible to provide additional inputs. These come either in the
%   form of a single string or of a string followed by a value.
%
%   'L'             Number of points in the interval [E(1),E(2)] at which
%                   the Floquet discriminant and alpha_21(E) are computed.
%                   Default: L=D.
%   'grid_spacing'  Controls how fine the grid on the interval [E(1),E(2)]
%                   used to find initial guesses of the main and auxiliary
%                   spectrum points is. Too large grid_spacings can lead
%                   to missed main and/or auxiliary spectrum points.
%                   Should be followed by a positive number.
%   'skip_normalization' Skips normalization steps during the forward scattering
%                   process that sometimes avoid numerical issues.
%   'quiet'         Turns off messages generated by then FNFT C library.
%                   (To turn off the messages generated by the mex
%                   interface functions, use MATLAB's warning and error
%                   commands instead.)
%   'default'       This option does nothing. Useful e.g. if the user wants
%                   to pass a string variable is_quiet, which is either
%                   "quiet" to turn it on or "default" to keep the default
%
% OUTPUTS
%   DEL             Real row vector of length L
%   al21            Real row vector of length L

% This file is part of FNFT.
%
% FNFT is free software; you can redistribute it and/or
% modify it under the terms of the version 2 of the GNU General
% Public License as published by the Free Software Foundation.
%
% FNFT is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program. If not, see <http://www.gnu.org/licenses/>.
%
% Contributors:
% Sander Wahls (KIT) 2025.
