% MEX_FNFT_KDVP Non-fast nonlinear Fourier transform for the Korteweg-de Vries equation
% with periodic boundaries. Note: Currently the option 'grid_spacing' must be set.
%
%   [main_spec, aux_spec, sheet_indices] = MEX_FNFT_KDVP(q, T, E)
%   [main_spec, aux_spec, sheet_indices] = MEX_FNFT_KDVP(q, T, E,
%                                                        OPTIONAL INPUTS)
%
% DESCRIPTION
%   Provides an interface to the C routine fnft_kdvp.
%
% INPUTS
%   q               Complex row vector of length D>1
%   T               Real 1x2 vector
%   E               Real 1x2 vector
%
% OPTIONAL INPUTS
%   It is possible to provide additional inputs. These come either in the
%   form of a single string or of a string followed by a value.
%
%   'grid_spacing'  Controls how fine the grid on the interval [E(1),E(2)]
%                   used to find initial guesses of the main and auxiliary
%                   spectrum points is. Too large grid_spacings can lead
%                   to missed main and/or auxiliary spectrum points.
%                   Should be followed by a positive number.
%   'niter'         Controls how many Newton iterations are most carried
%                   out when refining initial guesses for main and auxiliary
%                   spectral points. Should be followed by a non-negative
%                   integer.
%   'tol'           Controls when the Newton refinement stops. Should be
%                   followed by a scalar (<=0 indicates the default value).
%   'keep_degenerate' Add this option to keep degenerate points in the spectra.
%                   By default, they are removed.
%   'skip_normalization' Skips normalization steps during the forward scattering
%                   process that sometimes avoid numerical issues.
%   'spec_size'     Controls how much memory is preallocated for the main
%                   and auxiliary spectra. Use if the routine aborts
%                   with an error indicating that the memory was insufficient.
%                   Should be followed by a positive integer.
%   'quiet'         Turns off messages generated by then FNFT C library.
%                   (To turn off the messages generated by the mex
%                   interface functions, use MATLAB's warning and error
%                   commands instead.)
%   'default'       This option does nothing. Useful e.g. if the user wants
%                   to pass a string variable is_quiet, which is either
%                   "quiet" to turn it on or "default" to keep the default
%
% OUTPUTS
%   main_spec       Complex row vector of length 2*K
%   aux_spec        Complex row vector of length M
%   sheet_indices   Complex row vector of length M


% This file is part of FNFT.
%
% FNFT is free software; you can redistribute it and/or
% modify it under the terms of the version 2 of the GNU General
% Public License as published by the Free Software Foundation.
%
% FNFT is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program. If not, see <http://www.gnu.org/licenses/>.
%
% Contributors:
% Sander Wahls (KIT) 2025.
